print('Hello World')
print("Irene is a coder")
print("My first data science class")
print("My first summary")
print("Adding another line")
print("My last ")
print("My first summary")
print("Example of vs code")
